"""Updated models

Revision ID: 275208f92916
Revises: 627d25a8ac37
Create Date: 2019-02-14 12:39:11.319750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275208f92916'
down_revision = '627d25a8ac37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
